using System.IO;
using System.Text;

namespace tsbindgen.SinglePhase.Emit;

/// <summary>
/// Emits index.js stubs that throw at runtime.
/// Provides JavaScript module stubs for Node.js environments.
/// These stubs prevent accidental execution while allowing TypeScript type checking.
/// </summary>
public static class ModuleStubEmitter
{
    public static void Emit(BuildContext ctx, EmissionPlan plan, string outputDirectory)
    {
        ctx.Log("ModuleStubEmitter", "Generating index.js stub files...");

        var emittedCount = 0;

        // Process each namespace in order
        foreach (var nsOrder in plan.EmissionOrder.Namespaces)
        {
            var ns = nsOrder.Namespace;
            ctx.Log("ModuleStubEmitter", $"  Emitting stub for: {ns.Name}");

            // Generate stub content
            var content = GenerateStub(ns.Name);

            // Write to file: output/Namespace.Name/index.js
            var namespacePath = Path.Combine(outputDirectory, ns.Name);
            Directory.CreateDirectory(namespacePath);

            var outputFile = Path.Combine(namespacePath, "index.js");
            File.WriteAllText(outputFile, content);

            ctx.Log("ModuleStubEmitter", $"    → {outputFile}");
            emittedCount++;
        }

        ctx.Log("ModuleStubEmitter", $"Generated {emittedCount} stub files");
    }

    private static string GenerateStub(string namespaceName)
    {
        var sb = new StringBuilder();

        // File header
        sb.AppendLine("// Generated by tsbindgen - Single-Phase Architecture");
        sb.AppendLine($"// Namespace: {namespaceName}");
        sb.AppendLine("// Module Stub - Do Not Execute");
        sb.AppendLine();

        // Stub that throws
        sb.AppendLine("throw new Error(");
        sb.AppendLine($"  'Cannot import CLR namespace {namespaceName} in JavaScript runtime. ' +");
        sb.AppendLine("  'This module provides TypeScript type definitions only. ' +");
        sb.AppendLine("  'Actual implementation requires .NET runtime via Tsonic compiler.'");
        sb.AppendLine(");");

        return sb.ToString();
    }
}
